version: '3'
services:
  app:
    build: .
    depends_on:
      - db

  db:
    build: db/.
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
