name: Hello World App Workflow
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: |
          git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

  IntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - run: git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Start Database
        run: |
          docker build -t database ./db
          docker run --name employees -dp 33060:3306 database
          for i in {30..0}; do
            if docker exec employees mysqladmin ping -h localhost --silent; then
              echo "MySQL ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
          docker exec -i employees mysql -uroot -proot < db/test_db/employees.sql

      - name: Run Integration Tests
        run: mvn -Dtest=com.napier.sem.AppIntegrationTest test


  Build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: |
          git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Package and Run docker-compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
